dashboard/console/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'console'
urlpatterns = [
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/console/'), name='logout'),
    path('logs/<str:status>/', views.show_logs, name='show_logs'),
    path('detail/<int:pk>/', views.request_detail, name='details'),
    path('update_status/<int:pk>/<str:status>/', views.update_status, name='update-status'),
    path('profile/', views.profile, name='profile'),
    path('analytics/<str:feature>/', views.analytics_view, name='analytics'),
    path('sync_db/', views.sync_db, name='sync_db'),
    path('get_logs/<str:status>/', views.get_logs, name='get_logs'),
]

dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView


urlpatterns = [
    path('console/', include('console.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/console/', permanent=False), name='direct_to_login'),
    path('accounts/login/', RedirectView.as_view(url='/console/', permanent=False), name='redirect_to_login'),
]

dashboard/console/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Log(models.Model):
    # server_db_id : id of log in server db
    server_db_id = models.IntegerField()

    # string of format "%Y-%m-%d %H:%M:%S" eg. "2020-04-01 20:01:14", FORMAT = UTC
    timestamp = models.CharField(max_length=19, default='-')

    # emergency_ype contains string one of 'medical' & 'police'
    emergency_type = models.CharField(max_length=7, default='-')

    # core_id: id of sending device
    core_id = models.CharField(max_length=30, default='-')

    # latitude and longitude
    latitude = models.FloatField(default=-1.0)
    longitude = models.FloatField(default=-1.0)

    # accuracy
    accuracy = models.FloatField()

    # status: one of string: 'a' (active), 'w' (working), 'r' (resolved)
    status = models.CharField(max_length=1, default='a')

    def __str__(self):
        return str(self.id) + " " + str(self.timestamp) + " " + str(self.core_id)

    def save_log(self):
        self.save()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.TextField(max_length=500, blank=True)         # user.profile.location
    service = models.CharField(max_length=8, blank=True)            # user.profile.service
    phone = models.CharField(max_length=13, blank=True)             # user.profile.phone


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

dashboard/console/forms.py
from django import forms
from .models import Log, Profile
from django.contrib.auth.models import User
import datetime

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('service', 'location', 'phone')


YEARS = [x for x in range(2020, 2100)]

class AnalyticsForm(forms.Form):
    curr_date = datetime.date.today()       # get current date
    startDate = forms.DateField(label="Lower Limit:", initial="2020-04-01", widget=forms.SelectDateWidget(years=YEARS)) # set initial to starting date of project
    endDate = forms.DateField(label="Upper Limit:", initial=curr_date, widget=forms.SelectDateWidget(years=YEARS))      # set initial to today

dashboard/console/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from .models import Log
from .forms import UserForm, ProfileForm, AnalyticsForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.urls import reverse
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
import requests
import json
import googlemaps
from .context_processors import GOOGLE_API_KEY, MAPBOX_API_KEY
import datetime

def get_logs(request, status):
    # status filter:
    ## i : all logs
    ## a : new logs
    ## w : processing logs
    ## r : resolved logs

    if request.is_ajax():
        try:
            if status == 'i':
                logs = Log.objects.all()
            else:
                logs = Log.objects.filter(status=status)
        except Log.DoesNotExist:
            raise Http404("Log does not exist")
        logs_json = serializers.serialize('json', logs)
        return HttpResponse(logs_json, content_type='application/json')
    else:
        raise Http404("Log does not exist")


def sync_db(request):
    if request.method == 'POST':
        status = request.POST['status']
        response = requests.get('http://8199bb70.ngrok.io/rlogs/?status=a')     # get only the active records (only they will have new entries)
        if response.status_code == 200:
            incoming_logs = response.json()
            for log in incoming_logs:
                _server_db_id = log['id']
                _timestamp = log['timestamp']
                _core_id = log['core_id']
                try:
                    Log.objects.get(server_db_id=_server_db_id)
                except ObjectDoesNotExist:
                    l = Log(server_db_id=_server_db_id, timestamp=_timestamp, emergency_type=log['emergency_type'],
                            core_id=_core_id, latitude=log['latitude'], longitude=log['longitude'],
                            accuracy=log['accuracy'], status=log['status'])
                    l.save_log()
            return HttpResponse("status = " + str(status))
        else:
            return HttpResponse("No logs found!")


@login_required
def show_logs(request, status):
    if status == "all":
        return render(request, 'console/logs-all.html')
    elif status == "new":
        return render(request, 'console/logs-new.html')
    elif status == "processing":
        return render(request, 'console/logs-processing.html')
    elif status == "resolved":
        return render(request, 'console/logs-resolved.html')
    else:
        return render(request, 'console/404.html')


@login_required
def request_detail(request, pk):
    try:
        log = Log.objects.get(pk = pk)
        address = request.user.profile.location.strip()
        tokens = address.split(' ')
        source = '+'.join(tokens)
        return render(request, 'console/detail.html', {
            'log': log,
            'source': source,
        })
    except ObjectDoesNotExist:
        return render(request, 'console/404.html')

@login_required
def update_status(request, pk, status):
    log = get_object_or_404(Log, pk=pk)

    if status == "d":
        log.delete()
        return HttpResponseRedirect(reverse('console:show_logs', args=['all']))

    log.status = status
    log.save_log()

    patch_url = "http://8199bb70.ngrok.io/rlogs/?status=" + str(status) + "&id=" + str(log.server_db_id)
    response = requests.get(patch_url)

    if status == "w":
        return HttpResponseRedirect(reverse('console:show_logs', args=['processing']))
    elif status == "r":
        return HttpResponseRedirect(reverse('console:show_logs', args=['resolved']))


@login_required
@transaction.atomic
def profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return HttpResponseRedirect(reverse('console:profile'))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'console/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
def analytics_view(request, feature):
    if request.method == "POST":
        form = AnalyticsForm(request.POST)      # get current form
        min_date = datetime.datetime(int(form.data["startDate_year"]), int(form.data["startDate_month"]), int(form.data["startDate_day"]))   # get minimum date value
        max_date = datetime.datetime(int(form.data["endDate_year"]), int(form.data["endDate_month"]), int(form.data["endDate_day"]), 23, 59, 59)    # get maximum date value and set to last second of the day
    else:
        form = AnalyticsForm()
        min_date = datetime.datetime(2020, 1, 1)        # default minimum date value
        max_date = datetime.datetime.now()              # default maximum date value

    if feature == 'a':
        logs = Log.objects.all()
    elif feature == 'p':
        logs = Log.objects.filter(emergency_type = 'police')
    elif feature == 'm':
        logs = Log.objects.filter(emergency_type='medical')

    date_format = "%Y-%m-%d %H:%M:%S"       # provide a datetime format of char field timestamp of log
    data = []       # final data format: [[73.23, 23.56], [..., ...], ..., [lng, lat]]
    for log in logs:
        ts = log.timestamp      # get timestamp of log
        dt = datetime.datetime.strptime(ts, date_format)        # convert timestamp (char field) to datetime object
        if min_date < dt < max_date:
            position = [log.longitude, log.latitude]
            data.append(position)

    gmaps = googlemaps.Client(key = GOOGLE_API_KEY)
    geocode_result = gmaps.geocode(request.user.profile.location)       # geocode user's location
    lat = geocode_result[0]['geometry']['location']['lat']
    lng = geocode_result[0]['geometry']['location']['lng']

    data_js = json.dumps(data)      # JSON-ify data

    return render(request, 'console/analytics.html', {
        'data': data_js,
        'c_lat': lat,
        'c_lng': lng,
        'form': form,
        'MAPBOX_API_KEY': MAPBOX_API_KEY,
    })

dashboard/console/templates/console/analytics.html
{% extends 'console/base.html' %}

{% block content %}
    <!--main content start-->
<section id="main-content" xmlns:margin-top="http://www.w3.org/1999/xhtml">
        <section class="wrapper">

            <div class="row" style="margin: 10px;">
            <form id="date_filter" method="POST" class="post-form">
                {% csrf_token %}
                <div class="col-sm-3">
                    <table>
                    {{ form.as_table }}
                    </table>
                </div>
                <button type="submit" class="save btn btn-success"> <b>Update</b> </button>
            </form>
            </div>

            <div id="deck-container" style="height: 570px; margin: 20;"></div>

            <script type="text/javascript">
                const my_data = {{data}};

                const jsonInput = {"initialViewState": {"bearing": 0, "latitude": {{c_lat}}, "longitude": {{c_lng}}, "maxZoom": 16, "minZoom": 5, "pitch": 70, "zoom": 13},
                                      "layers": [{"@@type": "HexagonLayer", "autoHighlight": true, "coverage": 1, "data": my_data, "radius": 100, "elevationRange": [0, 200], "elevationScale": 5, "extruded": true, "opacity": 0.3, "getPosition": "@@=-", "id": "8e1a85a7-ba5e-4e34-9861-4bd4ab04d023", "pickable": true}],
                                      "mapStyle": "mapbox://styles/mapbox/light-v9",
                                      "views": [{"@@type": "MapView", "controller": true}]
                                   };
                const tooltip = {'text': 'Cases: {elevationValue}'};
                const customLibraries = null;

                const deck = createDeck({
                  mapboxApiKey: '{{MAPBOX_API_KEY}}',
                  container: document.getElementById('deck-container'),
                  jsonInput,
                  tooltip,
                  customLibraries
                });
            </script>

        </section>
    </section>
    <!--main content end-->
{% endblock %}

dashboard/console/templates/console/analytics_google_heatmap.html
{% extends 'console/base.html' %}

{% block content %}
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
            <script type="text/javascript">
                var data = {{data}};
                var loc;
                for(loc of data){

                }
            </script>
            <div id="floating-panel">
                <button onclick="toggleHeatmap()">Toggle Heatmap</button>
                <button onclick="changeRadius()">Change radius</button>
            </div>

            <div id="map" style="height: 650px;"> </div>

            <script>

              var map, heatmap;

              function initMap() {
                map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 14,
                  center: { lat: {{c_lat}}, lng: {{c_lng}} },
                  mapTypeId: 'hybrid'
                });

                heatmap = new google.maps.visualization.HeatmapLayer({
                  data: getPoints(),
                  map: map
                });
              }

              function toggleHeatmap() {
                heatmap.setMap(heatmap.getMap() ? null : map);
              }

              function changeRadius() {
                heatmap.set('radius', heatmap.get('radius') ? null : 20);
              }

              function getPoints() {
                var data = {{data}};
                var loc;
                var data_points = []
                for(loc of data){
                    data_points.push(new google.maps.LatLng(loc[0], loc[1]));
                }
                document.getElementById("output").innerHTML = data_points.length
                return data_points;
              }
            </script>

            <script async defer
                src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=visualization&callback=initMap">
            </script>
        </section>
        <p id="output"></p>
    </section>
    <!--main content end-->
{% endblock %}

dashboard/console/templates/console/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">

  <title>MeshSOS</title>

  <!-- Bootstrap CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- Custom styles -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />

  <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
  <script src=https://cdn.jsdelivr.net/npm/@deck.gl/jupyter-widget@~8.1.*/dist/index.js></script>
  <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css" rel="stylesheet" />

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
  <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
      <script src="{% static 'js/lte-ie7.js' %}"></script>
    <![endif]-->

    <!-- =======================================================
      Theme Name: NiceAdmin
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body>
  <!-- container section start -->
  <section id="container" class="">
    <!--header start-->

    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
      </div>

      <!--logo start-->
      <a href="{% url 'console:show_logs' status='all' %}" class="logo">Mesh <span class="lite">SOS</span></a>
      <!--logo end-->

      <div class="top-nav notification-row">
        <!-- option dropdown start-->
        <ul class="nav pull-right top-menu">
          <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="username">Options</span>
                            <b class="caret"></b>
                        </a>
            <ul class="dropdown-menu extended logout">
              <div class="log-arrow-up"></div>
              <li class="eborder-top">
                <a href="/console/profile/"><i class="icon_profile"></i> My Profile</a>
              </li>
              <li>
                <a href="{% url 'console:logout' %}"><i class="icon_key_alt"></i> Log Out</a>
              </li>
            </ul>
          </li>
        </ul>
        <!-- option dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="">
            <a class="" href="{% url 'console:show_logs' status='all' %}">
                          <i class="icon_house_alt"></i>
                          <span>All Logs</span>
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'console:show_logs' status='new' %}">
                          <i class="icon_document_alt"></i>
                          <span>New</span>
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'console:show_logs' status='processing' %}">
                          <i class="icon_document_alt"></i>
                          <span>Processing</span>
                      </a>
          </li>
          <li>
            <a class="" href="{% url 'console:show_logs' status='resolved' %}">
                          <i class="icon_document_alt"></i>
                          <span>Resolved</span>
                      </a>
          </li>
          <li class="sub-menu">
            <a href="javascript:;" class="">
                          <i class="icon_piechart"></i>
                          <span>Analytics</span>
                          <span class="menu-arrow arrow_carrot-right"></span>
                      </a>
            <ul class="sub">
              <li><a class="" href="{% url 'console:analytics' feature='a' %}">All Cases</a></li>
              <li><a class="" href="{% url 'console:analytics' feature='m' %}">Medical Cases</a></li>
              <li><a class="" href="{% url 'console:analytics' feature='p' %}">Police Cases</a></li>
            </ul>
          </li>

        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    {% block content %}
    {% endblock %}
    <!--main content end-->

    <div class="text-right">
      <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
  </section>
  <!-- container section end -->
  <!-- javascripts -->

  <script type="text/javascript">
        // script to update database at regular intervals

        var token = '{{csrf_token}}';

        function trigger_data_call(){
            $( document ).ready(function() {
                $.ajax({
                    headers: { "X-CSRFToken": token },
                    type:'POST',
                    url:'/console/sync_db/',
                    data:{
                        status:"a",
                    },
                    success:function(data){
                        console.log(data);
                    }
                });
            });
        }

        trigger_data_call();
        setInterval(trigger_data_call, 3000);
    </script>

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- nice scroll -->
  <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
  <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
  <!-- jquery knob -->
  <script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
  <!--custom script for all page-->
  <script src="{% static 'js/scripts.js' %}"></script>

  <script>
    //knob
    $(".knob").knob();
  </script>


</body>

</html>

dashboard/console/templates/console/detail.html
{% extends 'console/base.html' %}

{% block content %}
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="icon_info_alt"></i> REQUEST DETAILS </h3>
          </div>
        </div>
        <!-- page start-->
        <div class = "row">
          <div class="col-sm-4">
            <section class="panel">
              <header class="panel-heading">
                Request Details
              </header>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <td>Request ID</td>
                    <td>{{ log.id }}</td>
                  </tr>
                  <tr>
                    <td>Timestamp</td>
                    <td>{{ log.timestamp }}</td>
                  </tr>
                  <tr>
                    <td>Emergency</td>
                    <td>{{ log.emergency_type }}</td>
                  </tr>
                  <tr>
                    <td>Core ID</td>
                    <td>{{ log.core_id }}</td>
                  </tr>
                  <tr>
                    <td>Status</td>
                    {% if log.status == "a" %}
                    <td><span class="label label-danger">New</span></td>
                    {% elif log.status == "w" %}
                    <td><span class="label label-primary">Processing</span></td>
                    {% else %}
                    <td><span class="label label-success">Resolved</span></td>
                    {% endif %}
                  </tr>
                  <tr>
                    <td>Latitude</td>
                    <td>{{ log.latitude }}</td>
                  </tr>
                  <tr>
                    <td>Longitude</td>
                    <td>{{ log.longitude }}</td>
                  </tr>
                  <tr>
                    <td>Accuracy</td>
                    <td>{{ log.accuracy }}</td>
                  </tr>
                  <tr>
                    <td>Action</td>
                    <td>
                      <div class="btn-group">
                        {% if log.status == "a" %}
                        <a class="btn btn-primary" href="/console/update_status/{{log.pk}}/w/"><i class="icon_plus_alt2"></i> accept</a>
                        {% elif log.status == "w" %}
                        <a class="btn btn-success" href="/console/update_status/{{log.pk}}/r/"><i class="icon_check_alt2"></i> resolve</a>
                        {% else %}
                        <a class="btn btn-danger" href="/console/update_status/{{log.pk}}/d/"><i class="icon_close_alt2"></i> delete</a>
                        {% endif %}
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </section>
            <section>
              <a class="btn btn-info" href="https://www.google.com/maps/dir/?api=1&origin={{ source }}&destination={{ log.latitude }},{{ log.longitude }}" title="Bootstrap 3 themes generator" rel="noopener" target="_blank"><span class="icon_map"></span> Open Map In New Tab</a>
            </section>
          </div>
          <div class="col-sm-8">
            <iframe width="800"
                    height="600"
                    frameborder="5"
                    style="border:0"
                    src="https://www.google.com/maps/embed/v1/directions?key={{ GOOGLE_API_KEY }}&zoom=13&origin={{ source }}&destination={{ log.latitude }},{{ log.longitude }}&mode=driving"
                    allowfullscreen></iframe>
          </div>
        </div>
        <!-- page end-->
      </section>
    </section>
    <!--main content end-->
{% endblock %}

dashboard/console/templates/console/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
  <meta name="author" content="GeeksLabs">
  <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
  <link rel="shortcut icon" href="img/favicon.png">

  <title>MeshSOS - log in</title>

  <!-- Bootstrap CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- bootstrap theme -->
  <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
  <!--external css-->
  <!-- font icon -->
  <link href="{% static 'css/elegant-icons-style.css' %}" rel="stylesheet" />
  <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
  <!-- Custom styles -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <!-- =======================================================
      Theme Name: NiceAdmin
      Theme URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->
</head>

<body class="login-img3-body">

  <div class="container">

    <form class="login-form" action="index.html">
      <div class="login-wrap">
        <p class="login-img"><i class="icon_lock_alt"></i></p>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_profile"></i></span>
          <input type="text" class="form-control" placeholder="Username" autofocus>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><i class="icon_key_alt"></i></span>
          <input type="password" class="form-control" placeholder="Password">
        </div>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
        <button class="btn btn-info btn-lg btn-block" type="submit">Signup</button>
      </div>
    </form>
    <div class="text-right">
      <div class="credits">
          <!--
            All the links in the footer should remain intact.
            You can delete the links only if you purchased the pro version.
            Licensing information: https://bootstrapmade.com/license/
            Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
    </div>
  </div>


</body>

</html>

dashboard/console/templates/console/logs-processing.html
{% extends 'console/base.html' %}

{% block content %}
    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="page-header"><i class="fa fa fa-bars"></i> PROCESSING LOGS </h3>
          </div>
        </div>
        <!-- page start-->

        <div class="row">
          <div class="col-lg-12">
            <section class="panel">

            {% if logs %}
              <table class="table table-striped table-advance table-hover">
                <tbody>
                  <tr>
                    <th> Log ID</th>
                    <th><i class="icon_calendar"></i> Timestamp</th>
                    <th><i class="icon_error-triangle_alt"></i> Emergency</th>
                    <th><i class="icon_profile"></i> Core ID</th>
                    <th><i class="icon_check"></i> Status</th>
                    <th><i class="icon_cogs"></i> Action</th>
                  </tr>

                  {% for log in logs %}
                  <tr>
                      <td><a href="/console/detail/{{ log.pk }}/">{{ log.id }}</a></td>
                      <td>{{ log.timestamp }}</td>
                      <td>{{ log.emergency_type }}</td>
                      <td>{{ log.core_id }}</td>
                      <td><span class="label label-primary">Processing</span></td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-success" href="/console/update_status/{{log.pk}}/r/"><i class="icon_check_alt2"></i></a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}

                </tbody>
              </table>
            {% else %}
                <p>No logs are available.</p>
            {% endif %}

            </section>
          </div>
        </div>
        <!-- page end-->
      </section>
    </section>
    <!--main content end-->
{% endblock %}